DATASET:
  type: VIDEO_DATASET

VIDEO_DATASET:
  type: video
  sensor_type: mono   # Here, 'sensor_type' can be only 'mono' 
  base_path: ./data/videos/uploads
  settings: settings/ESP32.yaml
  name: new_upload.mp4

SYSTEM_STATE: 
  # This section is used for saving and reloading the system state: Sparse map + Loop closing state  
  load_state: False               # flag to enable SLAM state reloading (map state + loop closing state) and relocalization
  folder_path: results/slam_state  # default folder path (relative to root of this repository) where the system state is saved or reloaded
 

SAVE_TRAJECTORY:
  save_trajectory: True
  format_type: kitti             # supported formats: `tum`, `kitti`, `euroc`
  output_folder: results/metrics # relative to pyslam root folder 
  basename: trajectory           # basename of the trajectory saving output

# This section allows to change and override the default values of the global parameters contained in pyslam/config_parameters.py
# In this way, this yaml configuration can be used as a unique entry-point for launching experiments. 
GLOBAL_PARAMETERS: 
  #kUseVolumetricIntegration: True
  #kVolumetricIntegrationUseDepthEstimator: True
  #kLogsFolder: /tmp/pyslam_logs       # to redirect the prints of SLAM to the set folder
  